#!/usr/bin/with-contenv bash
# shellcheck shell=bash
NUSER=${USER_NAME:-sshadmin};

if [[ "${LOG_STDOUT,,}" == "true" ]]; then
    exec \
        s6-setuidgid "${NUSER}" s6-log +.* 1
else
    exec \
        s6-setuidgid "${NUSER}" s6-log n30 s10000000 S30000000 T !"gzip -nq9" /config/logs/openssh
fi
