#!/usr/bin/with-contenv bash
# shellcheck shell=bash
NUSER=${USER_NAME:-sshadmin};

exec 2>&1 \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${LISTEN_PORT:-2222}" \
        s6-setuidgid "${NUSER}" /usr/sbin/sshd -D -e 